// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appWrapper': string;
  'logo': string;
  'view': string;
}
export const cssExports: CssExports;
export default cssExports;
